### ISSUE TITLE
Deepgram SDK Fails with WebSocket Version 14.0 - Unexpected Keyword Argument extra_headers

### ISSUE THREAD

**Issue by artstyle46** [deepgram/deepgram-python-sdk#483]
## What is the current behavior?
 When using the Deepgram SDK with WebSocket version 14.0, the connection fails, and the following error is raised:
TypeError: got an unexpected keyword argument 'extra_headers'.
However, Deepgram works fine with WebSocket version 13.1.

## Steps to reproduce
 
Install WebSocket version 14.0
`pip install websockets==14.0`
Set up a Deepgram connection using the SDK.
`pip install deepgram-sdk==3.7.6`
Attempt to create a connection to Deepgram's API using 
`deepgram: DeepgramClient = DeepgramClient(DeepgramClientOptions(options={"keepalive": "true"} ))`
`dg_connection = deepgram.listen.asyncwebsocket.v("1")`
`options: LiveOptions = LiveOptions(
      model="nova-2-general",
      smart_format=True,
      punctuate=True,
      encoding="linear16",
      channels=1,
      sample_rate=8000,
      vad_events=True,
)`
`dg_connection.start(options=options)`
Observe the error: TypeError: got an unexpected keyword argument 'extra_headers'.

## Expected behavior

The connection should be established successfully without any errors when using WebSocket version 14.0, similar to the behavior with version 13.1.

## Please tell us about your environment
 
MacOS 14.6.1
python version v3.12.6

**Comment by kozzion** [comment]
Yeah have the same problem

**Comment by xzys** [comment]
The issue seems to be that the Python websockets library seems to accept `additional_headers` not `extra_headers`
https://github.com/python-websockets/websockets/blob/main/src/websockets/asyncio/client.py#L79

[Draft PR with fix](https://github.com/deepgram/deepgram-python-sdk/pull/486)

**Comment by kozzion** [comment]
Maybe it should look through the args for "extra headers, additional headers, more headers, suplementary headers"

**Comment by jrellisai** [comment]
I'm having the same issue. I'm using deepgram sdk 2.12, python 3.13.1, macOS 15.1.1 and websocket 13.
