### PR TITLE
Fix support for Python WebSocket >=14 while preserving backward compatibility

### LINKED ISSUE #483: Deepgram SDK Fails with WebSocket Version 14.0 - Unexpected Keyword Argument extra_headers
## What is the current behavior?
 When using the Deepgram SDK with WebSocket version 14.0, the connection fails, and the following error is raised:
TypeError: got an unexpected keyword argument 'extra_headers'.
However, Deepgram works fine with WebSocket version 13.1.

## Steps to reproduce
 
Install WebSocket version 14.0
`pip install websockets==14.0`
Set up a Deepgram connection using the SDK.
`pip install deepgram-sdk==3.7.6`
Attempt to create a connection to Deepgram's API using 
`deepgram: DeepgramClient = DeepgramClient(DeepgramClientOptions(options={"keepalive": "true"} ))`
`dg_connection = deepgram.listen.asyncwebsocket.v("1")`
`options: LiveOptions = LiveOptions(
      model="nova-2-general",
      smart_format=True,
      punctuate=True,
      encoding="linear16",
      channels=1,
      sample_rate=8000,
      vad_events=True,
)`
`dg_connection.start(options=options)`
Observe the error: TypeError: got an unexpected keyword argument 'extra_headers'.

## Expected behavior

The connection should be established successfully without any errors when using WebSocket version 14.0, similar to the behavior with version 13.1.

## Please tell us about your environment
 
MacOS 14.6.1
python version v3.12.6

### PR DESCRIPTION
**Pull request by fviard**
## Proposed changes
Websockets did a breaking change with version 14:
The client async base implementation changed and the "extra_headers" parameter was renamed to "additional_headers". 
(See issue #483)
A previous change solved the issue by pinning the websockets version to 12 or 13 (https://github.com/deepgram/deepgram-python-sdk/pull/487).

An alternative solution was proposed with the PR #486 but it was not satisfying as it was breaking the backward compatibility.

The purpose of the current PR is to support the new versions of python websockets by preserving support for the older 12 and 13 versions.

Fixes #483

## Types of changes

What types of changes does your code introduce to the community Python SDK?
_Put an `x` in the boxes that apply_

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update or tests (if none of the other choices apply)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [x] I have read the [CONTRIBUTING](../CONTRIBUTING.md) doc
- [x] I have lint'ed all of my code using repo standards
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

## Summary by CodeRabbit

- **Dependencies**
	- Updated `websockets` library version constraint to allow versions 12.0 and higher across multiple configuration files.

- **Compatibility**
	- Enhanced handling of WebSocket connections to support different versions of the `websockets` library.
	- Improved exception handling for closed connections to ensure robustness in the WebSocket client implementation.

### CODE REVIEW

**Comment by jpvajda** [comment]
@jjmaldonis  did you have any concerns on this approach?

**Review by jjmaldonis — DISMISSED** [review]
Very nice, thank you @fviard!

**Comment by fviard** [comment]
Re-pushed to fix the linter/typing issues. :-)

**Comment by fviard** [comment]
Sorry for the multiple pushs, I have reworked the fix to be more elegant.

It is now all good, including linter checks, and I have verified that it works correctly with all the websockets released versions (12, 13, 14) for sync and async clients.

**Comment by jjmaldonis** [comment]
I approved, and @jpvajda and team can merge + deploy depending on their timing.

**Comment by jpvajda** [comment]
I'm testing this change now with hopes to get it in our upcoming `3.9` release.

**Comment by jpvajda** [comment]
Test Results are promising:

@jjmaldonis  / @naomi-lgbt  let me know if this requires additional testing. 

- [live-async-microphone](https://github.com/deepgram/deepgram-python-sdk/tree/main/examples/speech-to-text/websocket/async_microphone) example runs successfully
- [live-microphone](https://github.com/deepgram/deepgram-python-sdk/tree/main/examples/speech-to-text/websocket/microphone) example runs successfully.
- [Daily Tests](https://github.com/deepgram/deepgram-python-sdk/tree/main/examples/speech-to-text/websocket/microphone)  had some failures, but I don't know if these ever passed

```bash

==================================================== short test summary info =====================================================
FAILED tests/daily_test/test_daily_async_listen_rest_url.py::test_daily_async_listen_rest_url[url0-options0-expected_output0] - AssertionError: Test ID: b00dc103a62ea2ccfc752ec0f646c7528ef5e729a9d7481d2a944253a9128ce2-29e7c8100617f70da4ae9da1921cb5071a0...
FAILED tests/daily_test/test_daily_async_listen_rest_url.py::test_daily_async_listen_rest_url[url1-options1-expected_output1] - AssertionError: Test ID: f3b6208a662156067a41bddd295a1a0a53ea34a268e27a8f1a9d7107aa99732f-29e7c8100617f70da4ae9da1921cb5071a0...
FAILED tests/daily_test/test_daily_async_listen_websocket.py::test_daily_async_listen_websocket[preamble-websocket.wav-options1-expected_output1] - AssertionError: Test ID: a6d1b12d5ce73a51a7b69ab156f0c98c72cdc1cfcf4a25f7b634c328cce4d760-42fc5ed98cabc1fa1a2f276301c27c46dd1...
FAILED tests/daily_test/test_daily_listen_rest_url.py::test_daily_listen_rest_url[url0-options0-expected_output0] - AssertionError: Test ID: b00dc103a62ea2ccfc752ec0f646c7528ef5e729a9d7481d2a944253a9128ce2-29e7c8100617f70da4ae9da1921cb5071a0...
FAILED tests/daily_test/test_daily_listen_rest_url.py::test_daily_listen_rest_url[url1-options1-expected_output1] - AssertionError: Test ID: f3b6208a662156067a41bddd295a1a0a53ea34a268e27a8f1a9d7107aa99732f-29e7c8100617f70da4ae9da1921cb5071a0...
FAILED tests/daily_test/test_daily_listen_websocket.py::test_daily_listen_websocket[preamble-websocket.wav-options1-expected_output1] - AssertionError: Test ID: a6d1b12d5ce73a51a7b69ab156f0c98c72cdc1cfcf4a25f7b634c328cce4d760-42fc5ed98cabc1fa1a2f276301c27c46dd1...
=============================== 6 failed, 10 passed, 19 deselected, 4 warnings in 73.09s (0:01:13) ===============================
```

**Review by jpvajda — APPROVED** [review]
